/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Main: typeof import('./components/Main.vue')['default']
    MvpChart: typeof import('./components/MvpChart/MvpChart.vue')['default']
    NavBar: typeof import('./components/NavBar/NavBar.vue')['default']
    PlayerList: typeof import('./components/PlayerList/PlayerList.vue')['default']
    PredictionsList: typeof import('./components/PredictionsList/PredictionsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
