/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Main: typeof import('./components/Main.vue')['default']
    MvpChart: typeof import('./components/MvpChart')['default']
    PlayerList: typeof import('./components/PlayerList')['default']
    PredictionsList: typeof import('./components/PredictionsList')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
